version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    container_name: fiidi_api
    build:
      context: fiidi-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: fiididb
      NODE_ENV: development
    volumes:
      - ./fiidi-api/:/usr/src/app/
      - ignore:/usr/src/app/scripts/
    depends_on:
      - rabbitmq
      - fiididb

  ui:
    container_name: fiidi_ui
    build:
      context: fiidi-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  fiididb:
    image: postgres:latest
    restart: always
    ports:
      - "5433:5433"
    environment:
      - PGPORT=5433
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fiididb
    volumes:
      - fiididb-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - fiididb

volumes:
  fiididb-data:
  ignore: