max_history: 150
check_period: 60 # in seconds
feeds:
- https://dev.to/feed
- https://www.30secondsofcode.org/feed
- https://hackernoon.com/tagged/frontend/feed
- https://css-tricks.com/feed/
- https://benfrain.com/feed/
- https://hackernoon.com/tagged/programming/feed
- https://hackernoon.com/tagged/react/feed
- https://hackernoon.com/tagged/coding/feed
- https://hackernoon.com/tagged/javascript/feed
- https://hackernoon.com/tagged/css/feed
- https://ashleynolan.co.uk/feed.xml
- https://dmitripavlutin.com/rss.xml
- https://feeds.feedburner.com/mariusschulz
- https://code.tutsplus.com/posts.atom
- https://alistapart.com/main/feed/
- https://feeds.feedburner.com/GiantRobotsSmashingIntoOtherGiantRobots
- https://feeds.feedburner.com/codyhouse/feeds
- https://feeds.feedburner.com/webdesignernews
- https://1stwebdesigner.com/feed/
- https://feeds.feedburner.com/philipwalton
- https://feeds.feedburner.com/csswizardry
- https://feeds.feedburner.com/perishablepress
- https://feeds.feedburner.com/brad-frosts-blog
- https://medium.com/feed/the-vue-point
- https://www.smashingmagazine.com/feed
- https://feeds.feedburner.com/robertnyman
- https://feeds.feedburner.com/24ways
- https://dailydevlinks.com/feed/
- https://cloudfour.com/feed/
- https://www.aaron-powell.com/posts/index.xml
- https://antoinevastel.com/feed.xml
- https://www.prestonlamb.com/blog-feed.xml
- https://stackoverflow.com/feeds/tag?tagnames=css&amp;sort=newest
- https://mathiasbynens.be/notes.atom
- https://www.designernews.co/?format=atom
- https://stackoverflow.com/feeds/tag?tagnames=reactjs&amp;sort=newest
- https://stackoverflow.com/feeds/tag?tagnames=javascript&amp;sort=newest
- https://stackoverflow.com/feeds/tag?tagnames=vue.js&amp;sort=newest
- https://bocoup.com/feed
- https://blog.mozilla.org/accessibility/feed/
- https://blogs.windows.com/msedgedev/feed/
- https://blog.mozilla.org/feed/
- https://www.sitepoint.com/feed/
- https://humanwhocodes.com/feeds/blog.xml
- https://blog.bitsrc.io/feed
- https://hacks.mozilla.org/feed/
- https://webplatform.news/feed.xml
- https://destroytoday.com/feeds/all
- https://stegosource.com/feed/
- https://blog.codepen.io/feed/
- https://joshwcomeau.com/rss.xml
- https://daverupert.com/atom.xml
- https://www.etsy.com/codeascraft/rss
- https://www.quirksmode.org/blog/atom.xml
- https://remotesynthesis.com/feed.xml
- https://www.stefanjudis.com/rss.xml
- https://tympanus.net/codrops/collective/feed/
- https://marcus.io/feed
- https://www.bram.us/feed/
- https://remysharp.com/feed.xml
- https://benmccormick.org/rss/
- https://tympanus.net/codrops/feed/
- https://www.matuzo.at/feed.xml
- https://davidflanagan.com/feed.xml
- https://blog.stephaniestimac.com/feed/feed.xml
- https://www.24a11y.com/feed/
- https://blog.benmyers.dev/feed.xml
- https://davidwalsh.name/feed/atom
- https://laurakalbag.com/posts/index.xml
- https://www.debugbear.com/blog/feed/rss
- https://hiddedevries.nl/rss/full/
- https://getflywheel.com/layout/feed/
- https://engineering.fb.com/feed/
- https://web.dev/feed.xml
- https://github.blog/feed/
- https://alwaystwisted.com/rss.php
- https://jakearchibald.com/posts.rss
- https://meiert.com/en/feed/
- https://lihautan.com/rss.xml
- https://webglfundamentals.org/atom.xml
- https://swizec.com/blog/feed
- https://stephaniewalter.design/feed/
- https://www.codeinwp.com/feed/
- https://catalin.red/feed
- https://bryanlrobinson.com/feed.xml
- https://geoffgraham.me/feed/
- https://dbushell.com/rss.xml
- https://www.sarasoueidan.com/blog/index.xml
- https://betterwebtype.com/feed.xml
- https://www.twilio.com/blog/tag/javascript/feed
- https://fossheim.io/feed.xml
- https://markosaric.com/feed/
- https://mxstbr.blog/feed.atom
- https://addyosmani.com/rss.xml
- https://americanexpress.io/feed.xml
- https://blog.isquaredsoftware.com/index.xml
- https://www.phpied.com/feed/
- https://michaelnthiessen.com/rss.xml
- https://www.impressivewebs.com/feed
- https://rachelandrew.co.uk/archives/rss.php
- https://feeds.dzone.com/webdev
- https://www.taniarascia.com/rss.xml
- https://darekkay.com/atom.xml
- https://www.trysmudford.com/blog/index.xml
- https://designmodo.com/feed/
- https://www.webdesignerdepot.com/feed/
- https://overreacted.io/rss.xml
- https://harrycresswell.com/articles/feed.xml
- https://www.xanthir.com/blog/atom/
- https://9elements.com/blog/rss/
- https://www.dan-davies.co.uk/feed
- https://justmarkup.com/feed/feed.xml
- https://blog.heroku.com/feed
- https://www.chenhuijing.com/feed.xml
- https://christianheilmann.com/feed/
- https://instagram-engineering.com/feed
- https://v8.dev/blog.atom
- https://greensock.com/blog/?rss=1
- https://sass-lang.com/feed.xml
- https://www.blog.gov.uk/feed/
- https://thecodebarbarian.com/feed.xml
- https://news.vuejs.org/feed.xml
- https://viljamis.com/atom.xml
- https://mike.sherov.com/rss.xml
- https://daveceddia.com/feed.xml
- https://nodejs.org/en/feed/blog.xml
- https://jrsinclair.com/index.rss
- https://heydonworks.com/feed.xml
- https://kentcdodds.com/blog/rss.xml
- https://www.madebymike.com.au/feed.xml
- https://css-irl.info/rss.xml
- https://www.shimmercat.com/feed.xml
- https://gomakethings.com/feed/index.xml
- https://inclusive-components.design/rss/
- https://feed.infoq.com/javascript/
- https://www.swyx.io/rss.xml
- https://www.youtube.com/feeds/videos.xml?channel_id=UC8butISFwT-Wl7EV0hUK0BQ
- https://snook.ca/jonathan/index.rdf
- https://accessibledreams.home.blog/feed/
- https://svelte.dev/blog/rss.xml
- https://piccalil.li/feed.xml
- https://reactjs.org/feed.xml
- https://bitsofco.de/rss/
- https://code.visualstudio.com/feed.xml
- https://volument.com/rss.xml
- https://trentwalton.com/feed.xml